server.port: 7001
spring:
  application:
    name: ch4-gateway
  cloud:
    gateway:
      routes:

      - id: service1_v1
        uri: http://127.0.0.1:7005/biz/k/2
        predicates:
        - Path=/abc

logging:
                              level:
                                org.springframework.cloud.gateway: TRACE
                                org.springframework.http.server.reactive: DEBUG
                                org.springframework.web.reactive: DEBUG
                                reactor.ipc.netty: DEBUG