server.port: 7001
spring:
  application:
    name: spring.cloud.gateway.route
  cloud:
    gateway:
      routes:
      - id: spring.cloud.biz
        uri: lb://spring.cloud.biz
        predicates:
        - Path=/**



logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG